views:
  - id: '3ca1fc31-047b-4093-a7da-8b83efeef3b3'
    name: 'Datapipe View 1'
    description: 'Default view for data pipe.'
    default: true
    type: 'data-pipe'
    modelObjects:
      - id: '6ba54ebc-6f00-4aa9-93fb-9fc312bc9f80'
      - id: 'c77d2e3b-e69a-4461-a9de-c969cd711677'
      - id: 'ad7aa9df-f78c-4724-9f19-72818d98852c'
      - id: '95c1e38b-d309-439b-8bcc-661380606768'
      - id: '1ecfee78-8402-41a6-afde-d8bb8f4a35ec'
      - id: '5e2ef6c8-3463-41d0-862a-afdac923dd0f'
  - id: '13d51b29-243a-4b58-8f8c-631318c4e40a'
    name: 'Datamodel View 1'
    description: 'Default view for data model.'
    default: true
    type: 'data-model'
    modelObjects: []
